# Generated by Django 3.1.4 on 2022-02-18 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220208_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(limit_choices_to={'role': 'SUBSCRIBER'}, to=settings.AUTH_USER_MODEL, verbose_name='suit'),
        ),
    ]
