# Generated by Django 3.1.4 on 2022-02-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20220208_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='time_created',
        ),
    ]
