# Generated by Django 3.1.4 on 2022-02-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_ticket_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='author',
        ),
    ]
